services:
  # --- BASE DE DONNÉES ---
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./app.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${DB_USER} -p${DB_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --- BACKEND (Spring Boot) ---
  backend:
    image: bdsdmiii/burgermanagement-backend:old
    container_name: spring_app
    restart: always
    env_file:
      - ./app.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads

  # --- FRONTEND (Angular + NGINX) ---
  frontend:
    image: bdsdmiii/burgermanagement-frontend:old
    container_name: angular_app
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4200:80"

# --- DÉCLARATION DES VOLUMES PERSISTANTS ---
volumes:
  db_data:
  backend_uploads:
